# **Bioinformatics Project - Computational Drug Discovery [Part 3] Descriptor Calculation and Dataset Preparation**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 3**, we will be calculating molecular descriptors that are essentially quantitative description of the compounds in the dataset. Finally, we will be preparing this into a dataset for subsequent model building in Part 4.

---

## **Download PaDEL-Descriptor**

In [ ]:
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh

--2020-06-09 16:58:49--  https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.zip [following]
--2020-06-09 16:58:50--  https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25768637 (25M) [application/zip]
Saving to: ‘padel.zip’

padel.zip           100%[===================>]  24.57M  40.2MB/s    in 0.6s

2020-06-09 16:58:51 (40.2 MB/s) - ‘padel.zip’ saved [25768637/25768637]

--2020-06-09 16:58:52--  https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.sh [following]
--2020-06-09 16:58:52--  https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 231 [text/plain]
Saving to: ‘padel.sh’

padel.sh            100%[===================>]     231  --.-KB/s    in 0s

2020-06-09 16:58:52 (11.1 MB/s) - ‘padel.sh’ saved [231/231]

In [3]:
!unzip -o -q padel.zip

In [4]:
!ls PaDEL-Descriptor

AtomPairs2DFingerprintCount.xml  KlekotaRothFingerprintCount.xml
AtomPairs2DFingerprinter.xml	 KlekotaRothFingerprinter.xml
config				 lib
Descriptors.xls			 license
descriptors.xml			 MACCSFingerprinter.xml
EStateFingerprinter.xml		 PaDEL-Descriptor.jar
ExtendedFingerprinter.xml	 PubchemFingerprinter.xml
Fingerprinter.xml		 SubstructureFingerprintCount.xml
GraphOnlyFingerprinter.xml	 SubstructureFingerprinter.xml

In [5]:
!apt-get install -y -qq default-jre
!java -version

Selecting previously unselected package at-spi2-common.
(Reading database ... 122813 files and directories currently installed.)
Preparing to unpack .../00-at-spi2-common_2.52.0-1build1_all.deb ...
Unpacking at-spi2-common (2.52.0-1build1) ...
Selecting previously unselected package libatspi2.0-0t64:amd64.
Preparing to unpack .../01-libatspi2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../02-libxtst6_2%3a1.2.3-1.1ubuntu0.1_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1.1ubuntu0.1) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../03-session-migration_0.3.9build1_amd64.deb ...
Unpacking session-migration (0.3.9build1) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../04-gsettings-desktop-schemas_46.1-0ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (46.1-0ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../05-at-spi2-core_2.52.0-1build1_amd64.deb ...
Unpacking at-spi2-core (2.52.0-1build1) ...
Selecting previously unselected package default-jre-headless.
Preparing to unpack .../06-default-jre-headless_2%3a1.21-75+exp1_amd64.deb ...
Unpacking default-jre-headless (2:1.21-75+exp1) ...
Selecting previously unselected package libatk1.0-0t64:amd64.
Preparing to unpack .../07-libatk1.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libatk-bridge2.0-0t64:amd64.
Preparing to unpack .../08-libatk-bridge2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../09-libxcomposite1_1%3a0.4.5-1build3_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build3) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../10-libgtk-3-common_3.24.41-4ubuntu1.3_all.deb ...
Unpacking libgtk-3-common (3.24.41-4ubuntu1.3) ...
Selecting previously unselected package libgtk-3-0t64:amd64.
Preparing to unpack .../11-libgtk-3-0t64_3.24.41-4ubuntu1.3_amd64.deb ...
Unpacking libgtk-3-0t64:amd64 (3.24.41-4ubuntu1.3) ...
Selecting previously unselected package openjdk-21-jre:amd64.
Preparing to unpack .../12-openjdk-21-jre_21.0.12.1+1-1~24.04.4_amd64.deb ...
Unpacking openjdk-21-jre:amd64 (21.0.12.1+1-1~24.04.4) ...
Selecting previously unselected package default-jre.
Preparing to unpack .../13-default-jre_2%3a1.21-75+exp1_amd64.deb ...
Unpacking default-jre (2:1.21-75+exp1) ...
Selecting previously unselected package fonts-dejavu-mono.
Preparing to unpack .../14-fonts-dejavu-mono_2.37-8_all.deb ...
Unpacking fonts-dejavu-mono (2.37-8) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../15-fonts-dejavu-core_2.37-8_all.deb ...
Unpacking fonts-dejavu-core (2.37-8) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../16-fonts-dejavu-extra_2.37-8_all.deb ...
Unpacking fonts-dejavu-extra (2.37-8) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../17-libxxf86dga1_2%3a1.1.5-1build1_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-1build1) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../18-x11-utils_7.7+6build2_amd64.deb ...
Unpacking x11-utils (7.7+6build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../19-libatk-wrapper-java_0.40.0-3build2_all.deb ...
Unpacking libatk-wrapper-java (0.40.0-3build2) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../20-libatk-wrapper-java-jni_0.40.0-3build2_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.40.0-3build2) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../21-libgtk-3-bin_3.24.41-4ubuntu1.3_amd64.deb ...
Unpacking libgtk-3-bin (3.24.41-4ubuntu1.3) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../22-librsvg2-common_2.58.0+dfsg-1ubuntu0.1_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.58.0+dfsg-1ubuntu0.1) ...
Setting up session-migration (0.3.9build1) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up default-jre-headless (2:1.21-75+exp1) ...
Setting up libxtst6:amd64 (2:1.2.3-1.1ubuntu0.1) ...
Setting up libxxf86dga1:amd64 (2:1.1.5-1build1) ...
Setting up libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up fonts-dejavu-mono (2.37-8) ...
Setting up fonts-dejavu-core (2.37-8) ...
Setting up librsvg2-common:amd64 (2.58.0+dfsg-1ubuntu0.1) ...
Setting up fonts-dejavu-extra (2.37-8) ...
Setting up at-spi2-common (2.52.0-1build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build3) ...
Setting up libgtk-3-common (3.24.41-4ubuntu1.3) ...
Setting up gsettings-desktop-schemas (46.1-0ubuntu1) ...
Setting up libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Setting up x11-utils (7.7+6build2) ...
Setting up libatk-wrapper-java (0.40.0-3build2) ...
Setting up libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.40.0-3build2) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.10+dfsg-3ubuntu3.3) ...
Processing triggers for fontconfig (2.15.0-1.1ubuntu2) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libglib2.0-0t64:amd64 (2.80.0-6ubuntu3.10) ...
Setting up libgtk-3-0t64:amd64 (3.24.41-4ubuntu1.3) ...
Setting up at-spi2-core (2.52.0-1build1) ...
Setting up libgtk-3-bin (3.24.41-4ubuntu1.3) ...
Setting up openjdk-21-jre:amd64 (21.0.12.1+1-1~24.04.4) ...
Setting up default-jre (2:1.21-75+exp1) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

[0.026s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.026s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
openjdk version "21.0.12.1" 2026-08-18
OpenJDK Runtime Environment (build 21.0.12.1+1-1-24.04.4-Ubuntu)
OpenJDK 64-Bit Server VM (build 21.0.12.1+1-1-24.04.4-Ubuntu, mixed mode, sharing)

In [6]:
%%writefile padel.sh
java -Xms2G -Xmx2G -Djava.awt.headless=true -jar ./PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PaDEL-Descriptor/PubchemFingerprinter.xml -dir ./ -file descriptors_output.csv

Writing padel.sh

## **Load bioactivity data**

Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

In [7]:
import pandas as pd

In [8]:
df3 = pd.read_csv('schistosoma mansoni_04_bioactivity_data_3class_pIC50.csv')

In [9]:
df3

,molecule_chembl_id,canonical_smiles,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50,bioactivity_class
0,CHEMBL576624,N#Cc1c(-c2csc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-],active,302.231,0.06826,0.0,9.0,6.455932,active
1,CHEMBL569420,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)s2)no[n+]1[O-],active,302.231,0.06826,0.0,9.0,6.397940,active
2,CHEMBL570121,N#Cc1c(-c2cc(F)cc(-c3no[n+]([O-])c3C#N)c2)no[n...,active,314.192,0.14586,0.0,8.0,6.318759,active
3,CHEMBL582970,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)cc2)no[n+]1...,active,296.202,0.00676,0.0,8.0,6.000000,active
4,CHEMBL575013,N#Cc1c(-c2cccc(-c3no[n+]([O-])c3C#N)c2)no[n+]1...,intermediate,296.202,0.00676,0.0,8.0,5.455932,intermediate
5,CHEMBL576265,N#Cc1c(C(=O)c2cccs2)no[n+]1[O-],active,221.197,0.47218,0.0,6.0,7.200659,active
6,CHEMBL583780,N#Cc1c(-c2cccs2)no[n+]1[O-],intermediate,193.187,0.90818,0.0,5.0,5.455932,intermediate
7,CHEMBL565242,N#Cc1c(-c2ccco2)no[n+]1[O-],intermediate,177.119,0.43968,0.0,5.0,5.552842,intermediate
8,CHEMBL570132,N#Cc1c(-c2ccc(O)cc2)no[n+]1[O-],inactive,203.157,0.55228,1.0,5.0,4.747147,inactive
9,CHEMBL576082,N#Cc1c(-c2ccc(-c3ccccc3)cc2)no[n+]1[O-],inactive,263.256,2.51368,0.0,4.0,4.801343,inactive
10,CHEMBL574801,Cc1ccc(-c2no[n+]([O-])c2C#N)cc1,inactive,201.185,1.15510,0.0,4.0,4.950782,inactive
11,CHEMBL578810,COc1ccc(-c2no[n+]([O-])c2C#N)cc1,inactive,217.184,0.85528,0.0,5.0,5.000000,inactive
12,CHEMBL569188,COc1cccc(-c2no[n+]([O-])c2C#N)c1,intermediate,217.184,0.85528,0.0,5.0,5.050610,intermediate
13,CHEMBL568961,COc1cc(-c2no[n+]([O-])c2C#N)cc(OC)c1OC,intermediate,277.236,0.87248,0.0,7.0,5.050610,intermediate
14,CHEMBL583779,COc1ccccc1-c1no[n+]([O-])c1C#N,intermediate,217.184,0.85528,0.0,5.0,5.102373,intermediate
15,CHEMBL576118,N#Cc1c(-c2ccc(F)cc2)no[n+]1[O-],intermediate,205.148,0.98578,0.0,4.0,5.102373,intermediate
16,CHEMBL571936,N#Cc1c(-c2cccc(O)c2)no[n+]1[O-],intermediate,203.157,0.55228,1.0,5.0,5.148742,intermediate
17,CHEMBL571712,N#Cc1c(-c2ccc(C(F)(F)F)cc2)no[n+]1[O-],intermediate,255.155,1.86548,0.0,4.0,5.148742,intermediate
18,CHEMBL567408,N#Cc1c(-c2ccc(Cl)cc2)no[n+]1[O-],intermediate,221.603,1.50008,0.0,4.0,5.397940,intermediate
19,CHEMBL585368,N#Cc1c(-c2ccc(Br)cc2)no[n+]1[O-],intermediate,266.054,1.60918,0.0,4.0,5.455932,intermediate
20,CHEMBL570130,N#Cc1c(-c2cccc(Cl)c2)no[n+]1[O-],intermediate,221.603,1.50008,0.0,4.0,5.455932,intermediate
21,CHEMBL574579,N#Cc1c(-c2cccc(Br)c2)no[n+]1[O-],intermediate,266.054,1.60918,0.0,4.0,5.552842,intermediate
22,CHEMBL585190,N#Cc1c(-c2ccc(F)c(Br)c2)no[n+]1[O-],intermediate,284.044,1.74828,0.0,4.0,5.552842,intermediate
23,CHEMBL571710,N#Cc1c(-c2cccc(C(F)(F)F)c2)no[n+]1[O-],intermediate,255.155,1.86548,0.0,4.0,5.602060,intermediate
24,CHEMBL570346,N#Cc1c(-c2cccc([N+](=O)[O-])c2)no[n+]1[O-],intermediate,232.155,0.75488,0.0,6.0,5.657577,intermediate
25,CHEMBL570345,O=C(c1cccs1)c1no[n+]([O-])c1C(=O)c1cccs1,active,306.324,1.89300,0.0,7.0,7.397940,active
26,CHEMBL500868,NC(=O)c1c(-c2ccccc2)no[n+]1[O-],inactive,205.173,0.07390,1.0,4.0,4.749580,inactive
27,CHEMBL574577,O=C(O)c1c(-c2ccccc2)no[n+]1[O-],active,206.157,0.67320,1.0,4.0,6.200659,active
28,CHEMBL567637,O=Cc1c(-c2ccccc2)no[n+]1[O-],active,190.158,0.78750,0.0,4.0,6.958607,active
29,CHEMBL567641,[O-][n+]1onc(-c2ccccc2)c1CO,inactive,192.174,0.46730,1.0,4.0,4.950782,inactive
30,CHEMBL574360,Cc1c(-c2ccccc2)no[n+]1[O-],inactive,176.175,1.28342,0.0,3.0,4.301030,inactive
31,CHEMBL336467,N#Cc1c(-c2ccccc2)no[n+]1[O-],intermediate,187.158,0.84668,0.0,4.0,5.200659,intermediate
32,CHEMBL3322357,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4nonc4S(=...,inactive,594.690,3.59860,0.0,9.0,4.301030,inactive
33,CHEMBL3322356,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4no[n+]([...,intermediate,610.689,2.83700,0.0,9.0,5.070581,intermediate
34,CHEMBL3322355,N#Cc1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)CC(=...,inactive,435.484,2.36858,0.0,7.0,4.301030,inactive
35,CHEMBL3322294,NC(=O)c1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)C...,inactive,453.499,1.59580,1.0,7.0,4.301030,inactive
36,CHEMBL3322293,N#Cc1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=O)N...,active,451.483,1.60698,0.0,7.0,6.455932,active
37,CHEMBL3322292,NC(=O)c1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=...,active,469.498,0.83420,1.0,7.0,7.080922,active
38,CHEMBL3322291,N#Cc1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,inactive,323.312,0.52308,0.0,6.0,4.301030,inactive
39,CHEMBL3322290,NC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,inactive,341.327,-0.24970,1.0,6.0,4.301030,inactive
40,CHEMBL3322289,COC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,inactive,356.338,0.43800,0.0,7.0,4.301030,inactive
41,CHEMBL3322288,N#Cc1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]1[O-],active,339.311,-0.23852,0.0,6.0,6.500313,active
42,CHEMBL3322287,NC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]...,active,357.326,-1.01130,1.0,6.0,8.000000,active
43,CHEMBL3322286,COC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+...,active,372.337,-0.32360,0.0,7.0,6.829738,active
44,CHEMBL1455957,CCc1nc2c([nH]1)c1no[n+]([O-])c1c1no[n+]([O-])c21,inactive,262.185,-0.32550,1.0,7.0,4.801343,inactive
45,CHEMBL1325877,COc1ccc(C(=O)c2no[n+]([O-])c2C(=O)c2ccc(OC)cc2...,active,354.318,1.78720,0.0,7.0,7.000000,active
46,CHEMBL1449349,O=C(CSc1ccccn1)Nc1nonc1[N+](=O)[O-],intermediate,281.253,1.10360,1.0,8.0,5.149967,intermediate
47,CHEMBL4871407,CCNc1sc(Br)c([N+](=O)[O-])c1[N+](=O)[O-],intermediate,296.102,2.75880,1.0,6.0,5.501689,intermediate
48,CHEMBL4852477,COC(=O)CS(=O)(=O)c1nnc(C(Cc2ccccc2)NC(=O)OC(C)...,active,425.463,1.82480,1.0,9.0,6.481486,active
49,CHEMBL1428415,CCN(c1ccccc1)S(=O)(=O)c1ccc(NC(=O)c2nc(S(C)(=O...,active,494.982,3.00100,1.0,7.0,6.677781,active
50,CHEMBL4858362,O=c1c(Cl)c(-n2cc(CO)nn2)cnn1-c1ccccc1,intermediate,303.709,0.95890,1.0,5.0,5.546682,intermediate
51,CHEMBL1337170,O=[N+]([O-])c1ccc2c(c1)S(=O)(=O)C=C2,intermediate,211.198,1.35280,0.0,4.0,5.696804,intermediate
52,CHEMBL1439384,COc1ccc([N+](=O)[O-])c(S(=O)(=O)c2ccc(Cl)cc2)n1,active,328.733,2.48460,0.0,6.0,7.221849,active
53,CHEMBL4846043,CCOC(=O)C(C(=O)OCC)C1=C(Br)C2=NOC3c4ccccc4C(=O...,active,460.280,3.25780,0.0,7.0,6.853872,active
54,CHEMBL1486739,COc1ccc(C(Nc2cc(C)ccn2)c2ccc3ccc(C)nc3c2O)cc1,active,385.467,5.16234,2.0,5.0,6.886057,active
55,CHEMBL5618241,C#CCN(Cc1nc(-c2ccccc2)oc1C)C1C[C@@H]2C[C@H]([C...,intermediate,362.517,5.15592,0.0,3.0,5.602060,intermediate
56,CHEMBL5619580,C[C@@H]1[C@H]2C[C@@H](C[C@H]1NCc1cn([C@@H]3OC[...,inactive,414.546,2.41310,4.0,5.0,4.240332,inactive

In [10]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [11]:
! cat molecule.smi | head -5

N#Cc1c(-c2csc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-]	CHEMBL576624
N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)s2)no[n+]1[O-]	CHEMBL569420
N#Cc1c(-c2cc(F)cc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-]	CHEMBL570121
N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)cc2)no[n+]1[O-]	CHEMBL582970
N#Cc1c(-c2cccc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-]	CHEMBL575013

In [12]:
! cat molecule.smi | wc -l

57

## **Calculate fingerprint descriptors**

### **Calculate PaDEL descriptors**

In [13]:
! cat padel.sh

java -Xms2G -Xmx2G -Djava.awt.headless=true -jar ./PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PaDEL-Descriptor/PubchemFingerprinter.xml -dir ./ -file descriptors_output.csv

In [14]:
! bash padel.sh

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Processing CHEMBL569420 in molecule.smi (2/57).
Processing CHEMBL576624 in molecule.smi (1/57).
Processing CHEMBL570121 in molecule.smi (3/57).
Processing CHEMBL582970 in molecule.smi (4/57). Average speed: 2.82 s/mol.
Processing CHEMBL575013 in molecule.smi (5/57). Average speed: 1.17 s/mol.
Processing CHEMBL576265 in molecule.smi (6/57). Average speed: 0.90 s/mol.
Processing CHEMBL583780 in molecule.smi (7/57). Average speed: 0.76 s/mol.
Processing CHEMBL565242 in molecule.smi (8/57). Average speed: 0.64 s/mol.
Processing CHEMBL570132 in molecule.smi (9/57). Average speed: 0.65 s/mol.
Processing CHEMBL576082 in molecule.smi (10/57). Average speed: 0.50 s/mol.
Processing CHEMBL574801 in molecule.smi (11/57). Average speed: 0.46 s/mol.
Processing CHEMBL578810 in molecule.smi (12/57). Average speed: 0.50 s/mol.
Processing CHEMBL569188 in molecule.smi (13/57). Average speed: 0.46 s/mol.
Processing CHEMBL568961 in molecule.smi (14/57). Average speed: 0.40 s/mol.
Processing CHEMBL583779 in molecule.smi (15/57). Average speed: 0.38 s/mol.
Processing CHEMBL576118 in molecule.smi (16/57). Average speed: 0.37 s/mol.
Processing CHEMBL571936 in molecule.smi (17/57). Average speed: 0.34 s/mol.
Processing CHEMBL571712 in molecule.smi (18/57). Average speed: 0.36 s/mol.
Processing CHEMBL567408 in molecule.smi (19/57). Average speed: 0.34 s/mol.
Processing CHEMBL585368 in molecule.smi (20/57). Average speed: 0.31 s/mol.
Processing CHEMBL570130 in molecule.smi (21/57). Average speed: 0.30 s/mol.
Processing CHEMBL574579 in molecule.smi (22/57). Average speed: 0.29 s/mol.
Processing CHEMBL585190 in molecule.smi (23/57). Average speed: 0.28 s/mol.
Processing CHEMBL571710 in molecule.smi (24/57). Average speed: 0.28 s/mol.
Processing CHEMBL570346 in molecule.smi (25/57). Average speed: 0.26 s/mol.
Processing CHEMBL570345 in molecule.smi (26/57). Average speed: 0.26 s/mol.
Processing CHEMBL500868 in molecule.smi (27/57). Average speed: 0.26 s/mol.
Processing CHEMBL574577 in molecule.smi (28/57). Average speed: 0.25 s/mol.
Processing CHEMBL567637 in molecule.smi (29/57). Average speed: 0.25 s/mol.
Processing CHEMBL567641 in molecule.smi (30/57). Average speed: 0.25 s/mol.
Processing CHEMBL574360 in molecule.smi (31/57). Average speed: 0.25 s/mol.
Processing CHEMBL336467 in molecule.smi (32/57). Average speed: 0.23 s/mol.
Processing CHEMBL3322357 in molecule.smi (33/57). Average speed: 0.24 s/mol.
Processing CHEMBL3322356 in molecule.smi (34/57). Average speed: 0.23 s/mol.
Processing CHEMBL3322355 in molecule.smi (35/57). Average speed: 0.25 s/mol.
Processing CHEMBL3322294 in molecule.smi (36/57). Average speed: 0.24 s/mol.
Processing CHEMBL3322293 in molecule.smi (37/57). Average speed: 0.24 s/mol.
Processing CHEMBL3322292 in molecule.smi (38/57). Average speed: 0.25 s/mol.
Processing CHEMBL3322291 in molecule.smi (39/57). Average speed: 0.25 s/mol.
Processing CHEMBL3322290 in molecule.smi (40/57). Average speed: 0.24 s/mol.
Processing CHEMBL3322289 in molecule.smi (41/57). Average speed: 0.24 s/mol.
Processing CHEMBL3322288 in molecule.smi (42/57). Average speed: 0.24 s/mol.
Processing CHEMBL3322287 in molecule.smi (43/57). Average speed: 0.24 s/mol.
Processing CHEMBL3322286 in molecule.smi (44/57). Average speed: 0.23 s/mol.
Processing CHEMBL1455957 in molecule.smi (45/57). Average speed: 0.24 s/mol.
Processing CHEMBL1325877 in molecule.smi (46/57). Average speed: 0.23 s/mol.
Processing CHEMBL1449349 in molecule.smi (47/57). Average speed: 0.23 s/mol.
Processing CHEMBL4871407 in molecule.smi (48/57). Average speed: 0.22 s/mol.
Processing CHEMBL4852477 in molecule.smi (49/57). Average speed: 0.22 s/mol.
Processing CHEMBL1428415 in molecule.smi (50/57). Average speed: 0.22 s/mol.
Processing CHEMBL4858362 in molecule.smi (51/57). Average speed: 0.22 s/mol.
Processing CHEMBL1337170 in molecule.smi (52/57). Average speed: 0.21 s/mol.
Processing CHEMBL1439384 in molecule.smi (53/57). Average speed: 0.21 s/mol.
Processing CHEMBL4846043 in molecule.smi (54/57). Average speed: 0.21 s/mol.
Processing CHEMBL1486739 in molecule.smi (55/57). Average speed: 0.21 s/mol.
Processing CHEMBL5618241 in molecule.smi (56/57). Average speed: 0.21 s/mol.
Processing CHEMBL5619580 in molecule.smi (57/57). Average speed: 0.21 s/mol.
Descriptor calculation completed in 11.805 secs . Average speed: 0.21 s/mol.

In [15]:
! ls -l

total 25312
-rw-r--r-- 1 root root   112662 Oct 28 22:34  descriptors_output.csv
drwxr-xr-x 3 root root     4096 Oct 28 20:51  __MACOSX
-rw-r--r-- 1 root root     3253 Oct 28 22:31  molecule.smi
drwxrwxr-x 4 root root     4096 Oct 28 20:51  PaDEL-Descriptor
-rw-r--r-- 1 root root      231 Oct 28 20:56  padel.sh
-rw-r--r-- 1 root root 25768637 Oct 28 20:50  padel.zip
drwxr-xr-x 1 root root     4096 Oct 26 22:18  sample_data
-rw-r--r-- 1 root root     7832 Oct 28 22:29 'schistosoma mansoni_04_bioactivity_data_3class_pIC50.csv'

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [16]:
df3_X = pd.read_csv('descriptors_output.csv')

In [17]:
df3_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL569420,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL576624,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL582970,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL570121,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL575013,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,CHEMBL576265,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,CHEMBL583780,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,CHEMBL565242,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,CHEMBL570132,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,CHEMBL574801,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,CHEMBL576082,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,CHEMBL578810,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,CHEMBL569188,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,CHEMBL568961,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,CHEMBL583779,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,CHEMBL576118,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,CHEMBL571936,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,CHEMBL567408,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,CHEMBL571712,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,CHEMBL585368,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,CHEMBL570130,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,CHEMBL574579,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,CHEMBL585190,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,CHEMBL571710,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,CHEMBL570346,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,CHEMBL570345,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,CHEMBL500868,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,CHEMBL574577,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,CHEMBL567637,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,CHEMBL567641,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,CHEMBL574360,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,CHEMBL336467,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,CHEMBL3322357,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,CHEMBL3322356,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,CHEMBL3322355,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,CHEMBL3322294,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,CHEMBL3322293,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,CHEMBL3322292,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,CHEMBL3322291,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,CHEMBL3322290,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,CHEMBL3322289,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,CHEMBL3322288,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,CHEMBL3322287,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,CHEMBL3322286,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,CHEMBL1455957,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,CHEMBL1449349,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,CHEMBL4871407,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,CHEMBL1325877,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,CHEMBL4852477,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,CHEMBL1428415,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,CHEMBL4858362,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,CHEMBL1337170,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,CHEMBL1439384,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53,CHEMBL4846043,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
54,CHEMBL5618241,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
55,CHEMBL1486739,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,CHEMBL5619580,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
13,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
18,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
26,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
27,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
29,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
30,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
31,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
32,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
33,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
34,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
35,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
36,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
37,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
38,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
39,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
41,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
42,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
43,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
44,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
45,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
46,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
47,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
48,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
49,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
50,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
51,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
52,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
53,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
54,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
55,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
56,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

## **Y variable**

### **Convert IC50 to pIC50**

In [19]:
df3_Y = df3['pIC50']
df3_Y

0     6.455932
1     6.397940
2     6.318759
3     6.000000
4     5.455932
5     7.200659
6     5.455932
7     5.552842
8     4.747147
9     4.801343
10    4.950782
11    5.000000
12    5.050610
13    5.050610
14    5.102373
15    5.102373
16    5.148742
17    5.148742
18    5.397940
19    5.455932
20    5.455932
21    5.552842
22    5.552842
23    5.602060
24    5.657577
25    7.397940
26    4.749580
27    6.200659
28    6.958607
29    4.950782
30    4.301030
31    5.200659
32    4.301030
33    5.070581
34    4.301030
35    4.301030
36    6.455932
37    7.080922
38    4.301030
39    4.301030
40    4.301030
41    6.500313
42    8.000000
43    6.829738
44    4.801343
45    7.000000
46    5.149967
47    5.501689
48    6.481486
49    6.677781
50    5.546682
51    5.696804
52    7.221849
53    6.853872
54    6.886057
55    5.602060
56    4.240332
Name: pIC50, dtype: float64

## **Combining X and Y variable**

In [20]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.455932
1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.397940
2,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.318759
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.000000
4,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.455932
5,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.200659
6,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.455932
7,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.552842
8,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.747147
9,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.801343
10,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.950782
11,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.000000
12,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.050610
13,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.050610
14,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.102373
15,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.102373
16,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.148742
17,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.148742
18,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.397940
19,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.455932
20,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.455932
21,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.552842
22,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.552842
23,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.602060
24,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.657577
25,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.397940
26,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.749580
27,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.200659
28,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.958607
29,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.950782
30,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
31,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.200659
32,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
33,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.070581
34,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
35,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
36,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.455932
37,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.080922
38,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
39,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
40,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
41,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.500313
42,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,8.000000
43,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.829738
44,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.801343
45,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.000000
46,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.149967
47,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.501689
48,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.481486
49,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.677781
50,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.546682
51,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.696804
52,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.221849
53,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.853872
54,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.886057
55,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.602060
56,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.240332

In [21]:
dataset3.to_csv('schistosoma mansoni_05_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**