# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [9]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.12/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.3.3)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.11.3)
Requirement already satisfied: url-normalize>=2.0 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (3.0.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)

## **Importing libraries**

In [10]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for coronavirus**

In [24]:
# Target search for schistossoma mansoni
target = new_client.target
target_query = target.search('schistosoma mansoni')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Schistosoma mansoni,Schistosoma mansoni,36.0,False,CHEMBL612893,[],ORGANISM,6183
1,[],Schistosoma japonicum,Schistosoma japonicum,17.0,False,CHEMBL612644,[],ORGANISM,6182
2,[],Schistosoma haematobium,Schistosoma haematobium,17.0,False,CHEMBL4296598,[],ORGANISM,6185
3,[],Schistosoma mansoni,Thioredoxin glutathione reductase,11.0,False,CHEMBL6110,"[{'accession': 'Q962Y6', 'component_descriptio...",SINGLE PROTEIN,6183
4,[],Schistosoma mansoni,Thioredoxin peroxidase,11.0,False,CHEMBL1293279,"[{'accession': 'O97161', 'component_descriptio...",SINGLE PROTEIN,6183
5,[],Schistosoma mansoni,Voltage-activated calcium channel beta 1 subunit,11.0,False,CHEMBL2363079,"[{'accession': 'Q95US7', 'component_descriptio...",SINGLE PROTEIN,6183
6,[],Schistosoma mansoni,Voltage-activated calcium channel beta 2 subunit,11.0,False,CHEMBL2363080,"[{'accession': 'Q962H3', 'component_descriptio...",SINGLE PROTEIN,6183
7,[],Schistosoma mansoni,Histone deacetylase 8,11.0,False,CHEMBL3797017,"[{'accession': 'A5H660', 'component_descriptio...",SINGLE PROTEIN,6183
8,[],Schistosoma mansoni,NAD-dependent protein deacetylase,11.0,False,CHEMBL4523517,"[{'accession': 'T1VXA1', 'component_descriptio...",SINGLE PROTEIN,6183
9,[],Schistosoma mansoni,"Dihydroorotate dehydrogenase (quinone), mitoch...",11.0,False,CHEMBL4523950,"[{'accession': 'G4VFD7', 'component_descriptio...",SINGLE PROTEIN,6183
10,[],Schistosoma mansoni,ATP-diphosphohydrolase 1,11.0,False,CHEMBL4879549,"[{'accession': 'Q7YTA4', 'component_descriptio...",SINGLE PROTEIN,6183
11,[],Schistosoma mansoni,Cathepsin B1 isotype 1,11.0,False,CHEMBL4888438,"[{'accession': 'Q8MNY2', 'component_descriptio...",SINGLE PROTEIN,6183
12,[],Schistosoma mansoni,Venus kinase receptor 2,11.0,False,CHEMBL5169215,"[{'accession': 'D5JEH1', 'component_descriptio...",SINGLE PROTEIN,6183
13,[],Schistosoma mansoni,DNA,10.0,False,CHEMBL2366043,[],NUCLEIC-ACID,6183

### **Select and retrieve bioactivity data for *SARS coronavirus 3C-like proteinase* (fifth entry)**

We will assign the fifth entry (which corresponds to the target protein, *coronavirus 3C-like proteinase*) to the ***selected_target*** variable

In [25]:
selected_target = targets.target_chembl_id[3]
selected_target

'CHEMBL6110'

Here, we will retrieve only bioactivity data for *coronavirus 3C-like proteinase* (CHEMBL3927) that are reported as IC$_{50}$ values in nM (nanomolar) unit.

In [26]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [27]:
df = pd.DataFrame.from_dict(res)

In [28]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,2931445,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.35
1,None,None,2931446,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.4
2,None,None,2931447,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.48

In [29]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [30]:
df.to_csv('bioactivity_data.csv', index=False)

## **Copying files to Google Drive**

Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [31]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Next, we create a **data** folder in our **Colab Notebooks** folder on Google Drive.

In [32]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data2"

mkdir: cannot create directory ‘/content/gdrive/My Drive/Colab Notebooks/data2’: File exists

In [33]:
! cp bioactivity_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [34]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

-rw------- 1 root root 34347 Aug 20 13:49 '/content/gdrive/My Drive/Colab Notebooks/data'

Let's see the CSV files that we have so far.

In [35]:
! ls

bioactivity_data.csv  gdrive  sample_data

Taking a glimpse of the **bioactivity_data.csv** file that we've just created.

In [36]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,modality,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,2931445,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,,,BAO_0000190,BAO_0000357,single protein format,N#Cc1c(-c2csc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-],,,CHEMBL1155233,J Med Chem,2009,"{'bei': '21.36', 'le': '0.42', 'lle': '6.39', 'sei': '4.21'}",,CHEMBL576624,,CHEMBL576624,6.46,0,http://www.openphacts.org/units/Nanomolar,853210,=,1,1,=,,IC50,nM,,350.0,CHEMBL6110,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,,,IC50,uM,UO_0000065,,0.35
,,2931446,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,,,BAO_0000190,BAO_0000357,single protein format,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)s2)no[n+]1[O-],,,CHEMBL1155233,J Med Chem,2009,"{'bei': '21.17', 'le': '0.42', 'lle': '6.33', 'sei': '4.17'}",,CHEMBL569420,,CHEMBL569420,6.40,0,http://www.openphacts.org/units/Nanomolar,853342,=,1,1,=,,IC50,nM,,400.0,CHEMBL6110,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,,,IC50,uM,UO_0000065,,0.4
,,2931447,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,,,BAO_0000190,BAO_0000357,single protein format,N#Cc1c(-c2cc(F)cc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-],,,CHEMBL1155233,J Med Chem,2009,"{'bei': '20.11', 'le': '0.38', 'lle': '6.17', 'sei': '4.12'}",,CHEMBL570121,,CHEMBL570121,6.32,0,http://www.openphacts.org/units/Nanomolar,853334,=,1,1,=,,IC50,nM,,480.0,CHEMBL6110,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,,,IC50,uM,UO_0000065,,0.48
,,2931448,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,,,BAO_0000190,BAO_0000357,single protein format,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)cc2)no[n+]1[O-],,,CHEMBL1155233,J Med Chem,2009,"{'bei': '20.26', 'le': '0.37', 'lle': '5.99', 'sei': '3.91'}",,CHEMBL582970,,CHEMBL582970,6.00,0,http://www.openphacts.org/units/Nanomolar,853333,=,1,1,=,,IC50,nM,,1000.0,CHEMBL6110,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,,,IC50,uM,UO_0000065,,1.0
,,2931449,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,,,BAO_0000190,BAO_0000357,single protein format,N#Cc1c(-c2cccc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-],,,CHEMBL1155233,J Med Chem,2009,"{'bei': '18.42', 'le': '0.34', 'lle': '5.45', 'sei': '3.55'}",,CHEMBL575013,,CHEMBL575013,5.46,0,http://www.openphacts.org/units/Nanomolar,853325,=,1,1,=,,IC50,nM,,3500.0,CHEMBL6110,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,,,IC50,uM,UO_0000065,,3.5
,,2931450,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,,,BAO_0000190,BAO_0000357,single protein format,N#Cc1c(C(=O)c2cccs2)no[n+]1[O-],,,CHEMBL1155233,J Med Chem,2009,"{'bei': '32.55', 'le': '0.66', 'lle': '6.73', 'sei': '7.67'}",,CHEMBL576265,,CHEMBL576265,7.20,0,http://www.openphacts.org/units/Nanomolar,853307,=,1,1,=,,IC50,nM,,63.0,CHEMBL6110,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,,,IC50,uM,UO_0000065,,0.063
,,2931451,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,,,BAO_0000190,BAO_0000357,single protein format,N#Cc1c(-c2cccs2)no[n+]1[O-],,,CHEMBL1155233,J Med Chem,2009,"{'bei': '28.24', 'le': '0.57', 'lle': '4.55', 'sei': '7.11'}",,CHEMBL583780,,CHEMBL583780,5.46,0,http://www.openphacts.org/units/Nanomolar,853289,=,1,1,=,,IC50,nM,,3500.0,CHEMBL6110,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,,,IC50,uM,UO_0000065,,3.5
,,2931452,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,,,BAO_0000190,BAO_0000357,single protein format,N#Cc1c(-c2ccco2)no[n+]1[O-],,,CHEMBL1155233,J Med Chem,2009,"{'bei': '31.35', 'le': '0.58', 'lle': '5.11', 'sei': '6.18'}",,CHEMBL565242,,CHEMBL565242,5.55,0,http://www.openphacts.org/units/Nanomolar,853288,=,1,1,=,,IC50,nM,,2800.0,CHEMBL6110,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,,,IC50,uM,UO_0000065,,2.8
,,2931453,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,,,BAO_0000190,BAO_0000357,single protein format,N#Cc1c(-c2ccc(O)cc2)no[n+]1[O-],,,CHEMBL1155233,J Med Chem,2009,"{'bei': '23.37', 'le': '0.43', 'lle': '4.20', 'sei': '4.89'}",,CHEMBL570132,,CHEMBL570132,4.75,0,http://www.openphacts.org/units/Nanomolar,853274,=,1,1,=,,IC50,nM,,17900.0,CHEMBL6110,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,,,IC50,uM,UO_0000065,,17.9

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [37]:
df2 = df[df.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,2931445,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.35
1,None,None,2931446,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.4
2,None,None,2931447,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.48
3,None,None,2931448,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,1.0
4,None,None,2931449,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
5,None,None,2931450,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.063
6,None,None,2931451,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
7,None,None,2931452,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
8,None,None,2931453,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,17.9
9,None,None,2931454,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,15.8
10,None,None,2931455,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,11.2
11,None,None,2931456,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,10.0
12,None,None,2931457,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.9
13,None,None,2931458,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.9
14,None,None,2931459,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.9
15,None,None,2931460,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.9
16,None,None,2931461,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.1
17,None,None,2931462,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.1
18,None,None,2931463,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,4.0
19,None,None,2931464,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
20,None,None,2931465,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
21,None,None,2931466,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
22,None,None,2931467,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
23,None,None,2931468,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.5
24,None,None,2931469,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.2
25,None,None,2931470,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.04
26,None,None,2931471,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,17.8
27,None,None,2931472,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.63
28,None,None,2931473,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.11
29,None,None,2931474,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,11.2
30,None,None,2931475,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
31,None,None,2931476,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,6.3
32,None,None,15025032,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
33,None,None,15025033,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.5
34,None,None,15025034,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
35,None,None,15025035,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
36,None,None,15025036,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.35
37,None,None,15025037,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.083
38,None,None,15025038,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
39,None,None,15025039,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
40,None,None,15025040,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
41,None,None,15025041,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.316
42,None,None,15025042,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.01
43,None,None,15025043,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.148
44,None,None,15025044,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,5.0
46,None,None,19408408,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,15.8
47,None,None,19408460,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.1
48,None,None,19408461,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.08
49,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155571,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811507,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.15
50,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155585,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.33
51,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155586,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.21
52,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155587,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.84
53,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155588,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.01
54,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155589,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.06
55,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155590,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.14
56,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155591,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.13
57,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129652,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5617298,Inhibition of Schistosoma mansoni TGR incubate...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.5
58,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129653,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5617298,Inhibition of Schistosoma mansoni TGR incubate...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,57.5

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [38]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [39]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [40]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [41]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [42]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [43]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL576624,N#Cc1c(-c2csc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-],active,350.0
1,CHEMBL569420,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)s2)no[n+]1[O-],active,400.0
2,CHEMBL570121,N#Cc1c(-c2cc(F)cc(-c3no[n+]([O-])c3C#N)c2)no[n...,active,480.0
3,CHEMBL582970,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)cc2)no[n+]1...,active,1000.0
4,CHEMBL575013,N#Cc1c(-c2cccc(-c3no[n+]([O-])c3C#N)c2)no[n+]1...,intermediate,3500.0
5,CHEMBL576265,N#Cc1c(C(=O)c2cccs2)no[n+]1[O-],active,63.0
6,CHEMBL583780,N#Cc1c(-c2cccs2)no[n+]1[O-],intermediate,3500.0
7,CHEMBL565242,N#Cc1c(-c2ccco2)no[n+]1[O-],intermediate,2800.0
8,CHEMBL570132,N#Cc1c(-c2ccc(O)cc2)no[n+]1[O-],inactive,17900.0
9,CHEMBL576082,N#Cc1c(-c2ccc(-c3ccccc3)cc2)no[n+]1[O-],inactive,15800.0
10,CHEMBL574801,Cc1ccc(-c2no[n+]([O-])c2C#N)cc1,inactive,11200.0
11,CHEMBL578810,COc1ccc(-c2no[n+]([O-])c2C#N)cc1,inactive,10000.0
12,CHEMBL569188,COc1cccc(-c2no[n+]([O-])c2C#N)c1,intermediate,8900.0
13,CHEMBL568961,COc1cc(-c2no[n+]([O-])c2C#N)cc(OC)c1OC,intermediate,8900.0
14,CHEMBL583779,COc1ccccc1-c1no[n+]([O-])c1C#N,intermediate,7900.0
15,CHEMBL576118,N#Cc1c(-c2ccc(F)cc2)no[n+]1[O-],intermediate,7900.0
16,CHEMBL571936,N#Cc1c(-c2cccc(O)c2)no[n+]1[O-],intermediate,7100.0
17,CHEMBL571712,N#Cc1c(-c2ccc(C(F)(F)F)cc2)no[n+]1[O-],intermediate,7100.0
18,CHEMBL567408,N#Cc1c(-c2ccc(Cl)cc2)no[n+]1[O-],intermediate,4000.0
19,CHEMBL585368,N#Cc1c(-c2ccc(Br)cc2)no[n+]1[O-],intermediate,3500.0
20,CHEMBL570130,N#Cc1c(-c2cccc(Cl)c2)no[n+]1[O-],intermediate,3500.0
21,CHEMBL574579,N#Cc1c(-c2cccc(Br)c2)no[n+]1[O-],intermediate,2800.0
22,CHEMBL585190,N#Cc1c(-c2ccc(F)c(Br)c2)no[n+]1[O-],intermediate,2800.0
23,CHEMBL571710,N#Cc1c(-c2cccc(C(F)(F)F)c2)no[n+]1[O-],intermediate,2500.0
24,CHEMBL570346,N#Cc1c(-c2cccc([N+](=O)[O-])c2)no[n+]1[O-],intermediate,2200.0
25,CHEMBL570345,O=C(c1cccs1)c1no[n+]([O-])c1C(=O)c1cccs1,active,40.0
26,CHEMBL500868,NC(=O)c1c(-c2ccccc2)no[n+]1[O-],inactive,17800.0
27,CHEMBL574577,O=C(O)c1c(-c2ccccc2)no[n+]1[O-],active,630.0
28,CHEMBL567637,O=Cc1c(-c2ccccc2)no[n+]1[O-],active,110.0
29,CHEMBL567641,[O-][n+]1onc(-c2ccccc2)c1CO,inactive,11200.0
30,CHEMBL574360,Cc1c(-c2ccccc2)no[n+]1[O-],inactive,50000.0
31,CHEMBL336467,N#Cc1c(-c2ccccc2)no[n+]1[O-],intermediate,6300.0
32,CHEMBL3322357,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4nonc4S(=...,inactive,50000.0
33,CHEMBL3322356,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4no[n+]([...,intermediate,8500.0
34,CHEMBL3322355,N#Cc1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)CC(=...,inactive,50000.0
35,CHEMBL3322294,NC(=O)c1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)C...,inactive,50000.0
36,CHEMBL3322293,N#Cc1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=O)N...,active,350.0
37,CHEMBL3322292,NC(=O)c1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=...,active,83.0
38,CHEMBL3322291,N#Cc1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,inactive,50000.0
39,CHEMBL3322290,NC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,inactive,50000.0
40,CHEMBL3322289,COC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,inactive,50000.0
41,CHEMBL3322288,N#Cc1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]1[O-],active,316.0
42,CHEMBL3322287,NC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]...,active,10.0
43,CHEMBL3322286,COC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+...,active,148.0
44,CHEMBL336467,N#Cc1c(-c2ccccc2)no[n+]1[O-],intermediate,5000.0
45,CHEMBL1455957,CCc1nc2c([nH]1)c1no[n+]([O-])c1c1no[n+]([O-])c21,inactive,15800.0
46,CHEMBL1325877,COc1ccc(C(=O)c2no[n+]([O-])c2C(=O)c2ccc(OC)cc2...,active,100.0
47,CHEMBL1449349,O=C(CSc1ccccn1)Nc1nonc1[N+](=O)[O-],intermediate,7080.0
48,CHEMBL4871407,CCNc1sc(Br)c([N+](=O)[O-])c1[N+](=O)[O-],intermediate,3150.0
49,CHEMBL4852477,COC(=O)CS(=O)(=O)c1nnc(C(Cc2ccccc2)NC(=O)OC(C)...,active,330.0
50,CHEMBL1428415,CCN(c1ccccc1)S(=O)(=O)c1ccc(NC(=O)c2nc(S(C)(=O...,active,210.0
51,CHEMBL4858362,O=c1c(Cl)c(-n2cc(CO)nn2)cnn1-c1ccccc1,intermediate,2840.0
52,CHEMBL1337170,O=[N+]([O-])c1ccc2c(c1)S(=O)(=O)C=C2,intermediate,2010.0
53,CHEMBL1439384,COc1ccc([N+](=O)[O-])c(S(=O)(=O)c2ccc(Cl)cc2)n1,active,60.0
54,CHEMBL4846043,CCOC(=O)C(C(=O)OCC)C1=C(Br)C2=NOC3c4ccccc4C(=O...,active,140.0
55,CHEMBL1486739,COc1ccc(C(Nc2cc(C)ccn2)c2ccc3ccc(C)nc3c2O)cc1,active,130.0
56,CHEMBL5618241,C#CCN(Cc1nc(-c2ccccc2)oc1C)C1C[C@@H]2C[C@H]([C...,intermediate,2500.0
57,CHEMBL5619580,C[C@@H]1[C@H]2C[C@@H](C[C@H]1NCc1cn([C@@H]3OC[...,inactive,57500.0

### **Alternative method**

In [44]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL576624,N#Cc1c(-c2csc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-],350.0
1,CHEMBL569420,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)s2)no[n+]1[O-],400.0
2,CHEMBL570121,N#Cc1c(-c2cc(F)cc(-c3no[n+]([O-])c3C#N)c2)no[n...,480.0
3,CHEMBL582970,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)cc2)no[n+]1...,1000.0
4,CHEMBL575013,N#Cc1c(-c2cccc(-c3no[n+]([O-])c3C#N)c2)no[n+]1...,3500.0
5,CHEMBL576265,N#Cc1c(C(=O)c2cccs2)no[n+]1[O-],63.0
6,CHEMBL583780,N#Cc1c(-c2cccs2)no[n+]1[O-],3500.0
7,CHEMBL565242,N#Cc1c(-c2ccco2)no[n+]1[O-],2800.0
8,CHEMBL570132,N#Cc1c(-c2ccc(O)cc2)no[n+]1[O-],17900.0
9,CHEMBL576082,N#Cc1c(-c2ccc(-c3ccccc3)cc2)no[n+]1[O-],15800.0
10,CHEMBL574801,Cc1ccc(-c2no[n+]([O-])c2C#N)cc1,11200.0
11,CHEMBL578810,COc1ccc(-c2no[n+]([O-])c2C#N)cc1,10000.0
12,CHEMBL569188,COc1cccc(-c2no[n+]([O-])c2C#N)c1,8900.0
13,CHEMBL568961,COc1cc(-c2no[n+]([O-])c2C#N)cc(OC)c1OC,8900.0
14,CHEMBL583779,COc1ccccc1-c1no[n+]([O-])c1C#N,7900.0
15,CHEMBL576118,N#Cc1c(-c2ccc(F)cc2)no[n+]1[O-],7900.0
16,CHEMBL571936,N#Cc1c(-c2cccc(O)c2)no[n+]1[O-],7100.0
17,CHEMBL571712,N#Cc1c(-c2ccc(C(F)(F)F)cc2)no[n+]1[O-],7100.0
18,CHEMBL567408,N#Cc1c(-c2ccc(Cl)cc2)no[n+]1[O-],4000.0
19,CHEMBL585368,N#Cc1c(-c2ccc(Br)cc2)no[n+]1[O-],3500.0
20,CHEMBL570130,N#Cc1c(-c2cccc(Cl)c2)no[n+]1[O-],3500.0
21,CHEMBL574579,N#Cc1c(-c2cccc(Br)c2)no[n+]1[O-],2800.0
22,CHEMBL585190,N#Cc1c(-c2ccc(F)c(Br)c2)no[n+]1[O-],2800.0
23,CHEMBL571710,N#Cc1c(-c2cccc(C(F)(F)F)c2)no[n+]1[O-],2500.0
24,CHEMBL570346,N#Cc1c(-c2cccc([N+](=O)[O-])c2)no[n+]1[O-],2200.0
25,CHEMBL570345,O=C(c1cccs1)c1no[n+]([O-])c1C(=O)c1cccs1,40.0
26,CHEMBL500868,NC(=O)c1c(-c2ccccc2)no[n+]1[O-],17800.0
27,CHEMBL574577,O=C(O)c1c(-c2ccccc2)no[n+]1[O-],630.0
28,CHEMBL567637,O=Cc1c(-c2ccccc2)no[n+]1[O-],110.0
29,CHEMBL567641,[O-][n+]1onc(-c2ccccc2)c1CO,11200.0
30,CHEMBL574360,Cc1c(-c2ccccc2)no[n+]1[O-],50000.0
31,CHEMBL336467,N#Cc1c(-c2ccccc2)no[n+]1[O-],6300.0
32,CHEMBL3322357,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4nonc4S(=...,50000.0
33,CHEMBL3322356,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4no[n+]([...,8500.0
34,CHEMBL3322355,N#Cc1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)CC(=...,50000.0
35,CHEMBL3322294,NC(=O)c1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)C...,50000.0
36,CHEMBL3322293,N#Cc1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=O)N...,350.0
37,CHEMBL3322292,NC(=O)c1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=...,83.0
38,CHEMBL3322291,N#Cc1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0
39,CHEMBL3322290,NC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0
40,CHEMBL3322289,COC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0
41,CHEMBL3322288,N#Cc1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]1[O-],316.0
42,CHEMBL3322287,NC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]...,10.0
43,CHEMBL3322286,COC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+...,148.0
44,CHEMBL336467,N#Cc1c(-c2ccccc2)no[n+]1[O-],5000.0
46,CHEMBL1455957,CCc1nc2c([nH]1)c1no[n+]([O-])c1c1no[n+]([O-])c21,15800.0
47,CHEMBL1325877,COc1ccc(C(=O)c2no[n+]([O-])c2C(=O)c2ccc(OC)cc2...,100.0
48,CHEMBL1449349,O=C(CSc1ccccn1)Nc1nonc1[N+](=O)[O-],7080.0
49,CHEMBL4871407,CCNc1sc(Br)c([N+](=O)[O-])c1[N+](=O)[O-],3150.0
50,CHEMBL4852477,COC(=O)CS(=O)(=O)c1nnc(C(Cc2ccccc2)NC(=O)OC(C)...,330.0
51,CHEMBL1428415,CCN(c1ccccc1)S(=O)(=O)c1ccc(NC(=O)c2nc(S(C)(=O...,210.0
52,CHEMBL4858362,O=c1c(Cl)c(-n2cc(CO)nn2)cnn1-c1ccccc1,2840.0
53,CHEMBL1337170,O=[N+]([O-])c1ccc2c(c1)S(=O)(=O)C=C2,2010.0
54,CHEMBL1439384,COc1ccc([N+](=O)[O-])c(S(=O)(=O)c2ccc(Cl)cc2)n1,60.0
55,CHEMBL4846043,CCOC(=O)C(C(=O)OCC)C1=C(Br)C2=NOC3c4ccccc4C(=O...,140.0
56,CHEMBL1486739,COc1ccc(C(Nc2cc(C)ccn2)c2ccc3ccc(C)nc3c2O)cc1,130.0
57,CHEMBL5618241,C#CCN(Cc1nc(-c2ccccc2)oc1C)C1C[C@@H]2C[C@H]([C...,2500.0
58,CHEMBL5619580,C[C@@H]1[C@H]2C[C@@H](C[C@H]1NCc1cn([C@@H]3OC[...,57500.0

In [45]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,standard_value,0
0,CHEMBL576624,N#Cc1c(-c2csc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-],350.0,active
1,CHEMBL569420,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)s2)no[n+]1[O-],400.0,active
2,CHEMBL570121,N#Cc1c(-c2cc(F)cc(-c3no[n+]([O-])c3C#N)c2)no[n...,480.0,active
3,CHEMBL582970,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)cc2)no[n+]1...,1000.0,active
4,CHEMBL575013,N#Cc1c(-c2cccc(-c3no[n+]([O-])c3C#N)c2)no[n+]1...,3500.0,intermediate
5,CHEMBL576265,N#Cc1c(C(=O)c2cccs2)no[n+]1[O-],63.0,active
6,CHEMBL583780,N#Cc1c(-c2cccs2)no[n+]1[O-],3500.0,intermediate
7,CHEMBL565242,N#Cc1c(-c2ccco2)no[n+]1[O-],2800.0,intermediate
8,CHEMBL570132,N#Cc1c(-c2ccc(O)cc2)no[n+]1[O-],17900.0,inactive
9,CHEMBL576082,N#Cc1c(-c2ccc(-c3ccccc3)cc2)no[n+]1[O-],15800.0,inactive
10,CHEMBL574801,Cc1ccc(-c2no[n+]([O-])c2C#N)cc1,11200.0,inactive
11,CHEMBL578810,COc1ccc(-c2no[n+]([O-])c2C#N)cc1,10000.0,inactive
12,CHEMBL569188,COc1cccc(-c2no[n+]([O-])c2C#N)c1,8900.0,intermediate
13,CHEMBL568961,COc1cc(-c2no[n+]([O-])c2C#N)cc(OC)c1OC,8900.0,intermediate
14,CHEMBL583779,COc1ccccc1-c1no[n+]([O-])c1C#N,7900.0,intermediate
15,CHEMBL576118,N#Cc1c(-c2ccc(F)cc2)no[n+]1[O-],7900.0,intermediate
16,CHEMBL571936,N#Cc1c(-c2cccc(O)c2)no[n+]1[O-],7100.0,intermediate
17,CHEMBL571712,N#Cc1c(-c2ccc(C(F)(F)F)cc2)no[n+]1[O-],7100.0,intermediate
18,CHEMBL567408,N#Cc1c(-c2ccc(Cl)cc2)no[n+]1[O-],4000.0,intermediate
19,CHEMBL585368,N#Cc1c(-c2ccc(Br)cc2)no[n+]1[O-],3500.0,intermediate
20,CHEMBL570130,N#Cc1c(-c2cccc(Cl)c2)no[n+]1[O-],3500.0,intermediate
21,CHEMBL574579,N#Cc1c(-c2cccc(Br)c2)no[n+]1[O-],2800.0,intermediate
22,CHEMBL585190,N#Cc1c(-c2ccc(F)c(Br)c2)no[n+]1[O-],2800.0,intermediate
23,CHEMBL571710,N#Cc1c(-c2cccc(C(F)(F)F)c2)no[n+]1[O-],2500.0,intermediate
24,CHEMBL570346,N#Cc1c(-c2cccc([N+](=O)[O-])c2)no[n+]1[O-],2200.0,intermediate
25,CHEMBL570345,O=C(c1cccs1)c1no[n+]([O-])c1C(=O)c1cccs1,40.0,active
26,CHEMBL500868,NC(=O)c1c(-c2ccccc2)no[n+]1[O-],17800.0,inactive
27,CHEMBL574577,O=C(O)c1c(-c2ccccc2)no[n+]1[O-],630.0,active
28,CHEMBL567637,O=Cc1c(-c2ccccc2)no[n+]1[O-],110.0,active
29,CHEMBL567641,[O-][n+]1onc(-c2ccccc2)c1CO,11200.0,inactive
30,CHEMBL574360,Cc1c(-c2ccccc2)no[n+]1[O-],50000.0,inactive
31,CHEMBL336467,N#Cc1c(-c2ccccc2)no[n+]1[O-],6300.0,intermediate
32,CHEMBL3322357,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4nonc4S(=...,50000.0,inactive
33,CHEMBL3322356,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4no[n+]([...,8500.0,intermediate
34,CHEMBL3322355,N#Cc1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)CC(=...,50000.0,inactive
35,CHEMBL3322294,NC(=O)c1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)C...,50000.0,inactive
36,CHEMBL3322293,N#Cc1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=O)N...,350.0,active
37,CHEMBL3322292,NC(=O)c1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=...,83.0,active
38,CHEMBL3322291,N#Cc1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0,inactive
39,CHEMBL3322290,NC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0,inactive
40,CHEMBL3322289,COC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0,inactive
41,CHEMBL3322288,N#Cc1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]1[O-],316.0,active
42,CHEMBL3322287,NC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]...,10.0,active
43,CHEMBL3322286,COC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+...,148.0,active
44,CHEMBL336467,N#Cc1c(-c2ccccc2)no[n+]1[O-],5000.0,intermediate
46,CHEMBL1455957,CCc1nc2c([nH]1)c1no[n+]([O-])c1c1no[n+]([O-])c21,15800.0,active
47,CHEMBL1325877,COc1ccc(C(=O)c2no[n+]([O-])c2C(=O)c2ccc(OC)cc2...,100.0,intermediate
48,CHEMBL1449349,O=C(CSc1ccccn1)Nc1nonc1[N+](=O)[O-],7080.0,intermediate
49,CHEMBL4871407,CCNc1sc(Br)c([N+](=O)[O-])c1[N+](=O)[O-],3150.0,active
50,CHEMBL4852477,COC(=O)CS(=O)(=O)c1nnc(C(Cc2ccccc2)NC(=O)OC(C)...,330.0,active
51,CHEMBL1428415,CCN(c1ccccc1)S(=O)(=O)c1ccc(NC(=O)c2nc(S(C)(=O...,210.0,intermediate
52,CHEMBL4858362,O=c1c(Cl)c(-n2cc(CO)nn2)cnn1-c1ccccc1,2840.0,intermediate
53,CHEMBL1337170,O=[N+]([O-])c1ccc2c(c1)S(=O)(=O)C=C2,2010.0,active
54,CHEMBL1439384,COc1ccc([N+](=O)[O-])c(S(=O)(=O)c2ccc(Cl)cc2)n1,60.0,active
55,CHEMBL4846043,CCOC(=O)C(C(=O)OCC)C1=C(Br)C2=NOC3c4ccccc4C(=O...,140.0,active
56,CHEMBL1486739,COc1ccc(C(Nc2cc(C)ccn2)c2ccc3ccc(C)nc3c2O)cc1,130.0,intermediate
57,CHEMBL5618241,C#CCN(Cc1nc(-c2ccccc2)oc1C)C1C[C@@H]2C[C@H]([C...,2500.0,inactive
58,CHEMBL5619580,C[C@@H]1[C@H]2C[C@@H](C[C@H]1NCc1cn([C@@H]3OC[...,57500.0,NaN
45,NaN,NaN,NaN,inactive

Saves dataframe to CSV file

In [46]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [47]:
! ls -l

total 48
-rw-r--r-- 1 root root 34347 Aug 20 13:48 bioactivity_data.csv
-rw-r--r-- 1 root root  3744 Aug 20 13:52 bioactivity_preprocessed_data.csv
drwx------ 5 root root  4096 Aug 20 13:48 gdrive
drwxr-xr-x 1 root root  4096 Aug 18 13:44 sample_data

Let's copy to the Google Drive

In [48]:
! cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [49]:
! ls "/content/gdrive/My Drive/Colab Notebooks/data"

'/content/gdrive/My Drive/Colab Notebooks/data'

---