# **Bioinformatics Project - Computational Drug Discovery [Part 1] Download Bioactivity Data (Concised version)**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 1**, we will be performing Data Collection and Pre-Processing from the ChEMBL Database.

Note for this Concised Version:
* Redundant code cells were deleted.
* Code cells for saving files to Google Drive has been deleted.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [ ]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading https://files.pythonhosted.org/packages/2e/48/0db29040c92726fcc6f99a5bc89e0ea8cf5a9d84753ebaaf53108792da2a/chembl-webresource-client-0.10.2.tar.gz (51kB)
     |████████████████████████████████| 61kB 2.1MB/s
Requirement already satisfied: urllib3 in /usr/local/lib/python3.6/dist-packages (from chembl_webresource_client) (1.24.3)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.6/dist-packages (from chembl_webresource_client) (2.23.0)
Collecting requests-cache>=0.4.7
  Downloading https://files.pythonhosted.org/packages/7f/55/9b1c40eb83c16d8fc79c5f6c2ffade04208b080670fbfc35e0a5effb5a92/requests_cache-0.5.2-py2.py3-none-any.whl
Requirement already satisfied: easydict in /usr/local/lib/python3.6/dist-packages (from chembl_webresource_client) (1.9)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2020.4.5.1)
Building wheels for collected packages: chembl-webresource-client
  Building wheel for chembl-webresource-client (setup.py) ... done
  Created wheel for chembl-webresource-client: filename=chembl_webresource_client-0.10.2-cp36-none-any.whl size=55661 sha256=a52d78c7928723755f476d68cdfcd640830e02a8ab2d24d68d28e0d0df1dcf8d
  Stored in directory: /root/.cache/pip/wheels/e6/96/19/3f042bfda7c669bfe24c8278477f57b0fbbf3e488b4c09e3a8
Successfully built chembl-webresource-client
Installing collected packages: requests-cache, chembl-webresource-client
Successfully installed chembl-webresource-client-0.10.2 requests-cache-0.5.2

## **Importing libraries**

In [4]:
# Instala a biblioteca caso o ambiente tenha sido reiniciado
!pip install -q chembl_webresource_client

# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

/usr/local/lib/python3.13/dist-packages/chembl_webresource_client/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

## **Search for Target protein**

### **Target search for Schistosoma mansoni**

In [5]:
# Target search for esquistossomose
target = new_client.target
target_query = target.search('schistosoma mansoni')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Schistosoma mansoni,Schistosoma mansoni,36.0,False,CHEMBL612893,[],ORGANISM,6183
1,[],Schistosoma japonicum,Schistosoma japonicum,17.0,False,CHEMBL612644,[],ORGANISM,6182
2,[],Schistosoma haematobium,Schistosoma haematobium,17.0,False,CHEMBL4296598,[],ORGANISM,6185
3,[],Schistosoma mansoni,Thioredoxin glutathione reductase,11.0,False,CHEMBL6110,"[{'accession': 'Q962Y6', 'component_descriptio...",SINGLE PROTEIN,6183
4,[],Schistosoma mansoni,Thioredoxin peroxidase,11.0,False,CHEMBL1293279,"[{'accession': 'O97161', 'component_descriptio...",SINGLE PROTEIN,6183
5,[],Schistosoma mansoni,Voltage-activated calcium channel beta 1 subunit,11.0,False,CHEMBL2363079,"[{'accession': 'Q95US7', 'component_descriptio...",SINGLE PROTEIN,6183
6,[],Schistosoma mansoni,Voltage-activated calcium channel beta 2 subunit,11.0,False,CHEMBL2363080,"[{'accession': 'Q962H3', 'component_descriptio...",SINGLE PROTEIN,6183
7,[],Schistosoma mansoni,Histone deacetylase 8,11.0,False,CHEMBL3797017,"[{'accession': 'A5H660', 'component_descriptio...",SINGLE PROTEIN,6183
8,[],Schistosoma mansoni,NAD-dependent protein deacetylase,11.0,False,CHEMBL4523517,"[{'accession': 'T1VXA1', 'component_descriptio...",SINGLE PROTEIN,6183
9,[],Schistosoma mansoni,"Dihydroorotate dehydrogenase (quinone), mitoch...",11.0,False,CHEMBL4523950,"[{'accession': 'G4VFD7', 'component_descriptio...",SINGLE PROTEIN,6183
10,[],Schistosoma mansoni,ATP-diphosphohydrolase 1,11.0,False,CHEMBL4879549,"[{'accession': 'Q7YTA4', 'component_descriptio...",SINGLE PROTEIN,6183
11,[],Schistosoma mansoni,Cathepsin B1 isotype 1,11.0,False,CHEMBL4888438,"[{'accession': 'Q8MNY2', 'component_descriptio...",SINGLE PROTEIN,6183
12,[],Schistosoma mansoni,Venus kinase receptor 2,11.0,False,CHEMBL5169215,"[{'accession': 'D5JEH1', 'component_descriptio...",SINGLE PROTEIN,6183
13,[],Schistosoma mansoni,DNA,10.0,False,CHEMBL2366043,[],NUCLEIC-ACID,6183

### **Select and retrieve bioactivity data for *Human Acetylcholinesterase* (first entry)**

We will assign the fifth entry (which corresponds to the target protein, *Human Acetylcholinesterase*) to the ***selected_target*** variable

In [6]:
selected_target = targets.target_chembl_id[3]
selected_target

'CHEMBL6110'

Here, we will retrieve only bioactivity data for (CHEMBL 6110) that are reported as pChEMBL values.

In [7]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [8]:
df = pd.DataFrame.from_dict(res)

In [9]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,2931445,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.35
1,None,None,2931446,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.4
2,None,None,2931447,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.48
3,None,None,2931448,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,1.0
4,None,None,2931449,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
5,None,None,2931450,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.063
6,None,None,2931451,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
7,None,None,2931452,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
8,None,None,2931453,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,17.9
9,None,None,2931454,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,15.8
10,None,None,2931455,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,11.2
11,None,None,2931456,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,10.0
12,None,None,2931457,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.9
13,None,None,2931458,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.9
14,None,None,2931459,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.9
15,None,None,2931460,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.9
16,None,None,2931461,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.1
17,None,None,2931462,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.1
18,None,None,2931463,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,4.0
19,None,None,2931464,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
20,None,None,2931465,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
21,None,None,2931466,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
22,None,None,2931467,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
23,None,None,2931468,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.5
24,None,None,2931469,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.2
25,None,None,2931470,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.04
26,None,None,2931471,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,17.8
27,None,None,2931472,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.63
28,None,None,2931473,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.11
29,None,None,2931474,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,11.2
30,None,None,2931475,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
31,None,None,2931476,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,6.3
32,None,None,15025032,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
33,None,None,15025033,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.5
34,None,None,15025034,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
35,None,None,15025035,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
36,None,None,15025036,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.35
37,None,None,15025037,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.083
38,None,None,15025038,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
39,None,None,15025039,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
40,None,None,15025040,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
41,None,None,15025041,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.316
42,None,None,15025042,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.01
43,None,None,15025043,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.148
44,None,None,15025044,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,5.0
45,None,None,15025045,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,Not Active,None,IC50,None,None,None,None
46,None,None,19408408,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,15.8
47,None,None,19408460,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.1
48,None,None,19408461,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.08
49,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155571,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811507,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.15
50,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155585,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.33
51,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155586,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.21
52,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155587,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.84
53,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155588,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.01
54,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155589,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.06
55,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155590,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.14
56,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155591,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.13
57,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129652,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5617298,Inhibition of Schistosoma mansoni TGR incubate...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.5
58,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129653,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5617298,Inhibition of Schistosoma mansoni TGR incubate...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,57.5

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [10]:
df.to_csv('schistosoma mansoni_01_bioactivity_data_raw.csv', index=False)

## **Handling missing data**
If any compounds has missing value for the **standard_value** and **canonical_smiles** column then drop it.

In [11]:
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

/tmp/ipykernel_3760/3852201246.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,2931445,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.35
1,None,None,2931446,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.4
2,None,None,2931447,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.48
3,None,None,2931448,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,1.0
4,None,None,2931449,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
5,None,None,2931450,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.063
6,None,None,2931451,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
7,None,None,2931452,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
8,None,None,2931453,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,17.9
9,None,None,2931454,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,15.8
10,None,None,2931455,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,11.2
11,None,None,2931456,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,10.0
12,None,None,2931457,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.9
13,None,None,2931458,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.9
14,None,None,2931459,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.9
15,None,None,2931460,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.9
16,None,None,2931461,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.1
17,None,None,2931462,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.1
18,None,None,2931463,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,4.0
19,None,None,2931464,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
20,None,None,2931465,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
21,None,None,2931466,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
22,None,None,2931467,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
23,None,None,2931468,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.5
24,None,None,2931469,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.2
25,None,None,2931470,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.04
26,None,None,2931471,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,17.8
27,None,None,2931472,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.63
28,None,None,2931473,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.11
29,None,None,2931474,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,11.2
30,None,None,2931475,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
31,None,None,2931476,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,6.3
32,None,None,15025032,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
33,None,None,15025033,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.5
34,None,None,15025034,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
35,None,None,15025035,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
36,None,None,15025036,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.35
37,None,None,15025037,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.083
38,None,None,15025038,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
39,None,None,15025039,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
40,None,None,15025040,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
41,None,None,15025041,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.316
42,None,None,15025042,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.01
43,None,None,15025043,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.148
44,None,None,15025044,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,5.0
46,None,None,19408408,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,15.8
47,None,None,19408460,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.1
48,None,None,19408461,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.08
49,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155571,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811507,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.15
50,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155585,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.33
51,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155586,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.21
52,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155587,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.84
53,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155588,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.01
54,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155589,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.06
55,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155590,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.14
56,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155591,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.13
57,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129652,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5617298,Inhibition of Schistosoma mansoni TGR incubate...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.5
58,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129653,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5617298,Inhibition of Schistosoma mansoni TGR incubate...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,57.5

In [12]:
len(df2.canonical_smiles.unique())

57

In [13]:
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,2931445,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.35
1,None,None,2931446,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.4
2,None,None,2931447,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.48
3,None,None,2931448,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,1.0
4,None,None,2931449,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
5,None,None,2931450,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.063
6,None,None,2931451,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
7,None,None,2931452,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
8,None,None,2931453,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,17.9
9,None,None,2931454,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,15.8
10,None,None,2931455,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,11.2
11,None,None,2931456,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,10.0
12,None,None,2931457,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.9
13,None,None,2931458,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.9
14,None,None,2931459,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.9
15,None,None,2931460,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.9
16,None,None,2931461,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.1
17,None,None,2931462,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.1
18,None,None,2931463,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,4.0
19,None,None,2931464,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
20,None,None,2931465,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.5
21,None,None,2931466,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
22,None,None,2931467,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.8
23,None,None,2931468,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.5
24,None,None,2931469,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.2
25,None,None,2931470,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.04
26,None,None,2931471,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,17.8
27,None,None,2931472,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.63
28,None,None,2931473,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.11
29,None,None,2931474,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,11.2
30,None,None,2931475,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
31,None,None,2931476,[],CHEMBL1048278,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,6.3
32,None,None,15025032,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
33,None,None,15025033,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,8.5
34,None,None,15025034,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
35,None,None,15025035,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
36,None,None,15025036,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.35
37,None,None,15025037,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.083
38,None,None,15025038,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
39,None,None,15025039,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
40,None,None,15025040,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,50.0
41,None,None,15025041,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.316
42,None,None,15025042,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.01
43,None,None,15025043,[],CHEMBL3365309,Inhibition of Schistosoma mansoni recombinant ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.148
46,None,None,19408408,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,15.8
47,None,None,19408460,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.1
48,None,None,19408461,[],CHEMBL4427075,Inhibition of Schistosoma mansoni TGR,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,7.08
49,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155571,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811507,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,3.15
50,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155585,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.33
51,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155586,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.21
52,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155587,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.84
53,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155588,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.01
54,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155589,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.06
55,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155590,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.14
56,"{'action_type': 'INHIBITOR', 'description': 'N...",None,23155591,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4811511,Inhibition of Schistosoma mansoni thioredoxin ...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,0.13
57,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129652,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5617298,Inhibition of Schistosoma mansoni TGR incubate...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,2.5
58,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26129653,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5617298,Inhibition of Schistosoma mansoni TGR incubate...,B,None,None,BAO_0000190,...,Schistosoma mansoni,Thioredoxin glutathione reductase,6183,None,None,IC50,uM,UO_0000065,None,57.5

## **Data pre-processing of the bioactivity data**

### **Combine the 3 columns (molecule_chembl_id,canonical_smiles,standard_value) and bioactivity_class into a DataFrame**

In [14]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL576624,N#Cc1c(-c2csc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-],350.0
1,CHEMBL569420,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)s2)no[n+]1[O-],400.0
2,CHEMBL570121,N#Cc1c(-c2cc(F)cc(-c3no[n+]([O-])c3C#N)c2)no[n...,480.0
3,CHEMBL582970,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)cc2)no[n+]1...,1000.0
4,CHEMBL575013,N#Cc1c(-c2cccc(-c3no[n+]([O-])c3C#N)c2)no[n+]1...,3500.0
5,CHEMBL576265,N#Cc1c(C(=O)c2cccs2)no[n+]1[O-],63.0
6,CHEMBL583780,N#Cc1c(-c2cccs2)no[n+]1[O-],3500.0
7,CHEMBL565242,N#Cc1c(-c2ccco2)no[n+]1[O-],2800.0
8,CHEMBL570132,N#Cc1c(-c2ccc(O)cc2)no[n+]1[O-],17900.0
9,CHEMBL576082,N#Cc1c(-c2ccc(-c3ccccc3)cc2)no[n+]1[O-],15800.0
10,CHEMBL574801,Cc1ccc(-c2no[n+]([O-])c2C#N)cc1,11200.0
11,CHEMBL578810,COc1ccc(-c2no[n+]([O-])c2C#N)cc1,10000.0
12,CHEMBL569188,COc1cccc(-c2no[n+]([O-])c2C#N)c1,8900.0
13,CHEMBL568961,COc1cc(-c2no[n+]([O-])c2C#N)cc(OC)c1OC,8900.0
14,CHEMBL583779,COc1ccccc1-c1no[n+]([O-])c1C#N,7900.0
15,CHEMBL576118,N#Cc1c(-c2ccc(F)cc2)no[n+]1[O-],7900.0
16,CHEMBL571936,N#Cc1c(-c2cccc(O)c2)no[n+]1[O-],7100.0
17,CHEMBL571712,N#Cc1c(-c2ccc(C(F)(F)F)cc2)no[n+]1[O-],7100.0
18,CHEMBL567408,N#Cc1c(-c2ccc(Cl)cc2)no[n+]1[O-],4000.0
19,CHEMBL585368,N#Cc1c(-c2ccc(Br)cc2)no[n+]1[O-],3500.0
20,CHEMBL570130,N#Cc1c(-c2cccc(Cl)c2)no[n+]1[O-],3500.0
21,CHEMBL574579,N#Cc1c(-c2cccc(Br)c2)no[n+]1[O-],2800.0
22,CHEMBL585190,N#Cc1c(-c2ccc(F)c(Br)c2)no[n+]1[O-],2800.0
23,CHEMBL571710,N#Cc1c(-c2cccc(C(F)(F)F)c2)no[n+]1[O-],2500.0
24,CHEMBL570346,N#Cc1c(-c2cccc([N+](=O)[O-])c2)no[n+]1[O-],2200.0
25,CHEMBL570345,O=C(c1cccs1)c1no[n+]([O-])c1C(=O)c1cccs1,40.0
26,CHEMBL500868,NC(=O)c1c(-c2ccccc2)no[n+]1[O-],17800.0
27,CHEMBL574577,O=C(O)c1c(-c2ccccc2)no[n+]1[O-],630.0
28,CHEMBL567637,O=Cc1c(-c2ccccc2)no[n+]1[O-],110.0
29,CHEMBL567641,[O-][n+]1onc(-c2ccccc2)c1CO,11200.0
30,CHEMBL574360,Cc1c(-c2ccccc2)no[n+]1[O-],50000.0
31,CHEMBL336467,N#Cc1c(-c2ccccc2)no[n+]1[O-],6300.0
32,CHEMBL3322357,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4nonc4S(=...,50000.0
33,CHEMBL3322356,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4no[n+]([...,8500.0
34,CHEMBL3322355,N#Cc1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)CC(=...,50000.0
35,CHEMBL3322294,NC(=O)c1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)C...,50000.0
36,CHEMBL3322293,N#Cc1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=O)N...,350.0
37,CHEMBL3322292,NC(=O)c1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=...,83.0
38,CHEMBL3322291,N#Cc1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0
39,CHEMBL3322290,NC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0
40,CHEMBL3322289,COC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0
41,CHEMBL3322288,N#Cc1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]1[O-],316.0
42,CHEMBL3322287,NC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]...,10.0
43,CHEMBL3322286,COC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+...,148.0
46,CHEMBL1455957,CCc1nc2c([nH]1)c1no[n+]([O-])c1c1no[n+]([O-])c21,15800.0
47,CHEMBL1325877,COc1ccc(C(=O)c2no[n+]([O-])c2C(=O)c2ccc(OC)cc2...,100.0
48,CHEMBL1449349,O=C(CSc1ccccn1)Nc1nonc1[N+](=O)[O-],7080.0
49,CHEMBL4871407,CCNc1sc(Br)c([N+](=O)[O-])c1[N+](=O)[O-],3150.0
50,CHEMBL4852477,COC(=O)CS(=O)(=O)c1nnc(C(Cc2ccccc2)NC(=O)OC(C)...,330.0
51,CHEMBL1428415,CCN(c1ccccc1)S(=O)(=O)c1ccc(NC(=O)c2nc(S(C)(=O...,210.0
52,CHEMBL4858362,O=c1c(Cl)c(-n2cc(CO)nn2)cnn1-c1ccccc1,2840.0
53,CHEMBL1337170,O=[N+]([O-])c1ccc2c(c1)S(=O)(=O)C=C2,2010.0
54,CHEMBL1439384,COc1ccc([N+](=O)[O-])c(S(=O)(=O)c2ccc(Cl)cc2)n1,60.0
55,CHEMBL4846043,CCOC(=O)C(C(=O)OCC)C1=C(Br)C2=NOC3c4ccccc4C(=O...,140.0
56,CHEMBL1486739,COc1ccc(C(Nc2cc(C)ccn2)c2ccc3ccc(C)nc3c2O)cc1,130.0
57,CHEMBL5618241,C#CCN(Cc1nc(-c2ccccc2)oc1C)C1C[C@@H]2C[C@H]([C...,2500.0
58,CHEMBL5619580,C[C@@H]1[C@H]2C[C@@H](C[C@H]1NCc1cn([C@@H]3OC[...,57500.0

Saves dataframe to CSV file

In [15]:
df3.to_csv('Schistosoma mansoni_02_bioactivity_data_preprocessed.csv', index=False)

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [16]:
df4 = pd.read_csv('Schistosoma mansoni_02_bioactivity_data_preprocessed.csv')

In [17]:
bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")

In [18]:
bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL576624,N#Cc1c(-c2csc(-c3no[n+]([O-])c3C#N)c2)no[n+]1[O-],350.0,active
1,CHEMBL569420,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)s2)no[n+]1[O-],400.0,active
2,CHEMBL570121,N#Cc1c(-c2cc(F)cc(-c3no[n+]([O-])c3C#N)c2)no[n...,480.0,active
3,CHEMBL582970,N#Cc1c(-c2ccc(-c3no[n+]([O-])c3C#N)cc2)no[n+]1...,1000.0,active
4,CHEMBL575013,N#Cc1c(-c2cccc(-c3no[n+]([O-])c3C#N)c2)no[n+]1...,3500.0,intermediate
5,CHEMBL576265,N#Cc1c(C(=O)c2cccs2)no[n+]1[O-],63.0,active
6,CHEMBL583780,N#Cc1c(-c2cccs2)no[n+]1[O-],3500.0,intermediate
7,CHEMBL565242,N#Cc1c(-c2ccco2)no[n+]1[O-],2800.0,intermediate
8,CHEMBL570132,N#Cc1c(-c2ccc(O)cc2)no[n+]1[O-],17900.0,inactive
9,CHEMBL576082,N#Cc1c(-c2ccc(-c3ccccc3)cc2)no[n+]1[O-],15800.0,inactive
10,CHEMBL574801,Cc1ccc(-c2no[n+]([O-])c2C#N)cc1,11200.0,inactive
11,CHEMBL578810,COc1ccc(-c2no[n+]([O-])c2C#N)cc1,10000.0,inactive
12,CHEMBL569188,COc1cccc(-c2no[n+]([O-])c2C#N)c1,8900.0,intermediate
13,CHEMBL568961,COc1cc(-c2no[n+]([O-])c2C#N)cc(OC)c1OC,8900.0,intermediate
14,CHEMBL583779,COc1ccccc1-c1no[n+]([O-])c1C#N,7900.0,intermediate
15,CHEMBL576118,N#Cc1c(-c2ccc(F)cc2)no[n+]1[O-],7900.0,intermediate
16,CHEMBL571936,N#Cc1c(-c2cccc(O)c2)no[n+]1[O-],7100.0,intermediate
17,CHEMBL571712,N#Cc1c(-c2ccc(C(F)(F)F)cc2)no[n+]1[O-],7100.0,intermediate
18,CHEMBL567408,N#Cc1c(-c2ccc(Cl)cc2)no[n+]1[O-],4000.0,intermediate
19,CHEMBL585368,N#Cc1c(-c2ccc(Br)cc2)no[n+]1[O-],3500.0,intermediate
20,CHEMBL570130,N#Cc1c(-c2cccc(Cl)c2)no[n+]1[O-],3500.0,intermediate
21,CHEMBL574579,N#Cc1c(-c2cccc(Br)c2)no[n+]1[O-],2800.0,intermediate
22,CHEMBL585190,N#Cc1c(-c2ccc(F)c(Br)c2)no[n+]1[O-],2800.0,intermediate
23,CHEMBL571710,N#Cc1c(-c2cccc(C(F)(F)F)c2)no[n+]1[O-],2500.0,intermediate
24,CHEMBL570346,N#Cc1c(-c2cccc([N+](=O)[O-])c2)no[n+]1[O-],2200.0,intermediate
25,CHEMBL570345,O=C(c1cccs1)c1no[n+]([O-])c1C(=O)c1cccs1,40.0,active
26,CHEMBL500868,NC(=O)c1c(-c2ccccc2)no[n+]1[O-],17800.0,inactive
27,CHEMBL574577,O=C(O)c1c(-c2ccccc2)no[n+]1[O-],630.0,active
28,CHEMBL567637,O=Cc1c(-c2ccccc2)no[n+]1[O-],110.0,active
29,CHEMBL567641,[O-][n+]1onc(-c2ccccc2)c1CO,11200.0,inactive
30,CHEMBL574360,Cc1c(-c2ccccc2)no[n+]1[O-],50000.0,inactive
31,CHEMBL336467,N#Cc1c(-c2ccccc2)no[n+]1[O-],6300.0,intermediate
32,CHEMBL3322357,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4nonc4S(=...,50000.0,inactive
33,CHEMBL3322356,O=C(C1CCCCC1)N1CC(=O)N2CCc3ccc(OCCCOc4no[n+]([...,8500.0,intermediate
34,CHEMBL3322355,N#Cc1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)CC(=...,50000.0,inactive
35,CHEMBL3322294,NC(=O)c1nonc1COc1ccc2c(c1)C1CN(C(=O)C3CCCCC3)C...,50000.0,inactive
36,CHEMBL3322293,N#Cc1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=O)N...,350.0,active
37,CHEMBL3322292,NC(=O)c1c(COc2ccc3c(c2)C2CN(C(=O)C4CCCCC4)CC(=...,83.0,active
38,CHEMBL3322291,N#Cc1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0,inactive
39,CHEMBL3322290,NC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0,inactive
40,CHEMBL3322289,COC(=O)c1nonc1C(=O)N1CC(=O)N2CCc3ccccc3C2C1,50000.0,inactive
41,CHEMBL3322288,N#Cc1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]1[O-],316.0,active
42,CHEMBL3322287,NC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+]...,10.0,active
43,CHEMBL3322286,COC(=O)c1c(C(=O)N2CC(=O)N3CCc4ccccc4C3C2)no[n+...,148.0,active
44,CHEMBL1455957,CCc1nc2c([nH]1)c1no[n+]([O-])c1c1no[n+]([O-])c21,15800.0,inactive
45,CHEMBL1325877,COc1ccc(C(=O)c2no[n+]([O-])c2C(=O)c2ccc(OC)cc2...,100.0,active
46,CHEMBL1449349,O=C(CSc1ccccn1)Nc1nonc1[N+](=O)[O-],7080.0,intermediate
47,CHEMBL4871407,CCNc1sc(Br)c([N+](=O)[O-])c1[N+](=O)[O-],3150.0,intermediate
48,CHEMBL4852477,COC(=O)CS(=O)(=O)c1nnc(C(Cc2ccccc2)NC(=O)OC(C)...,330.0,active
49,CHEMBL1428415,CCN(c1ccccc1)S(=O)(=O)c1ccc(NC(=O)c2nc(S(C)(=O...,210.0,active
50,CHEMBL4858362,O=c1c(Cl)c(-n2cc(CO)nn2)cnn1-c1ccccc1,2840.0,intermediate
51,CHEMBL1337170,O=[N+]([O-])c1ccc2c(c1)S(=O)(=O)C=C2,2010.0,intermediate
52,CHEMBL1439384,COc1ccc([N+](=O)[O-])c(S(=O)(=O)c2ccc(Cl)cc2)n1,60.0,active
53,CHEMBL4846043,CCOC(=O)C(C(=O)OCC)C1=C(Br)C2=NOC3c4ccccc4C(=O...,140.0,active
54,CHEMBL1486739,COc1ccc(C(Nc2cc(C)ccn2)c2ccc3ccc(C)nc3c2O)cc1,130.0,active
55,CHEMBL5618241,C#CCN(Cc1nc(-c2ccccc2)oc1C)C1C[C@@H]2C[C@H]([C...,2500.0,intermediate
56,CHEMBL5619580,C[C@@H]1[C@H]2C[C@@H](C[C@H]1NCc1cn([C@@H]3OC[...,57500.0,inactive

Saves dataframe to CSV file

In [19]:
df5.to_csv('Schistosoma mansoni_03_bioactivity_data_curated.csv', index=False)

In [20]:
! zip acetylcholinesterase.zip *.csv

  adding: schistosoma mansoni_01_bioactivity_data_raw.csv (deflated 89%)
  adding: Schistosoma mansoni_02_bioactivity_data_preprocessed.csv (deflated 72%)
  adding: Schistosoma mansoni_03_bioactivity_data_curated.csv (deflated 75%)

In [21]:
! ls -l

total 60
-rw-r--r-- 1 root root  6749 Oct 28 21:16  acetylcholinesterase.zip
drwxr-xr-x 1 root root  4096 Oct 26 22:18  sample_data
-rw-r--r-- 1 root root 34347 Oct 28 21:15 'schistosoma mansoni_01_bioactivity_data_raw.csv'
-rw-r--r-- 1 root root  3695 Oct 28 21:16 'Schistosoma mansoni_02_bioactivity_data_preprocessed.csv'
-rw-r--r-- 1 root root  4268 Oct 28 21:16 'Schistosoma mansoni_03_bioactivity_data_curated.csv'

---